document.addEventListener('DOMContentLoaded', () => {
  const products = {
    'celik-kepenk': ['Çelik Kepenk','YÜKSEK GÜVENLİK','assets/project-kepenk.jpg','Mağaza, depo ve endüstriyel alanlarda dayanıklı fiziksel koruma.','Mağaza|Depo|Fabrika|Ticari alan','Dayanıklı yapı|Motor uyumu|Farklı profil seçenekleri','Standart veya yoğun kullanım motoru|Kumanda ve alıcı kartı|UPS desteği','Otomatik Kepenk|Alüminyum Kepenk'],
    'seffaf-kepenk': ['Şeffaf Kepenk','GÖRÜNÜRLÜK + KORUMA','assets/real-hero.jpeg','Vitrin görünürlüğünü korumak isteyen mağazalar için kontrollü güvenlik çözümü.','Mağaza vitrini|AVM içi alan|Showroom|Sergi alanı','Vitrin görünürlüğü|Modern görünüm|Otomasyon uyumu','Şeffaf panel veya polikarbon seçenek|Motorlu kullanım|Emniyet sensörü','Delikli Çelik Kepenk|Fotoselli Kapı'],
    'otomatik-panjur': ['Otomatik Panjur','KONFOR + MAHREMİYET','assets/category-6.jpg','Konut ve ticari yapılarda ışık, mahremiyet ve kullanım konforu.','Konut|Ofis|Villa|Ticari cephe','Uzaktan kontrol|Gölgeleme|Kompakt yapı','Alüminyum profil|Motor ve kumanda|Renk seçenekleri','Otomatik Kepenk|Seksiyonel Kapı'],
    'otomatik-kapilar': ['Otomatik Kapılar','KONTROLLÜ GEÇİŞ','assets/category-3.jpg','Yoğun girişlerde erişilebilir ve kontrollü geçiş sistemleri.','Mağaza|Hastane|Ofis|Kamu girişi','Temassız geçiş|Yoğun kullanıma uygun|Erişilebilirlik','Sensör|Kontrol kartı|Kanat ve ray seçenekleri','Fotoselli Kapı|Döner Kapı'],
    'fotoselli-kapi': ['Fotoselli Kapı','TEMASSIZ GEÇİŞ','assets/category-3.jpg','Sensörle çalışan, yoğun girişler için hızlı otomatik kapı çözümü.','Market|Ofis|Hastane|Mağaza','Hızlı açılma|Temassız kullanım|Ayarlanabilir sensör','Tek/çift kanat|Sensör ayarı|Kontrol ünitesi','Otomatik Kapı|Döner Kapı'],
    'garaj-kapisi': ['Garaj Kapısı','ALAN VERİMLİ GİRİŞ','assets/category-4.jpg','Konut ve ticari garajlar için seksiyonel veya kepenk tipi otomasyon.','Villa|Apartman|Otopark|Ticari garaj','Tavan alanını kullanır|Motorlu kontrol|Yalıtımlı panel seçeneği','Seksiyonel panel|Motor ve ray|Emniyet sistemi','Otomatik Kepenk|Yana Kayar Kapı'],
    'bahce-kapisi-motorlari': ['Bahçe Kapısı Motorları','DIŞ MEKÂN OTOMASYONU','assets/category-1.jpg','Yana kayar veya kanatlı bahçe kapıları için motor ve kontrol sistemi.','Villa|Site|Fabrika|Bahçe girişi','Uzaktan kontrol|Araç geçiş konforu|Kontrol sistemi entegrasyonu','Kapı ağırlığına uygun motor|Fotosel|Kumanda ve flaşör','Kollu Bariyer|Yana Kayar Motor'],
    'bariyer-sistemleri': ['Kollu Bariyer Sistemleri','ARAÇ GEÇİŞ KONTROLÜ','assets/category-2.jpg','Otopark ve tesis girişlerinde kontrollü araç geçişi.','Otopark|Site|Fabrika|Tesis girişi','Hızlı geçiş|Kontrol entegrasyonu|Yoğun kullanım seçeneği','Kol uzunluğu|Motor kapasitesi|Fotosel ve kumanda','Bahçe Kapısı Motoru|Otomatik Geçiş'],
    'kepenk-motorlari': ['Kepenk Motorları','DOĞRU KAPASİTE','assets/category-5.jpg','Kepenk ölçüsü, ağırlığı ve kullanım sıklığına göre motor seçenekleri.','Yeni sistem|Motor değişimi|Yoğun kullanım|Bakım','Uygun kapasite|Kontrollü hareket|Kumanda uyumu','Tork kapasitesi|Limit ayarı|Alıcı kartı uyumu','Standart Motor|Yoğun Kullanım Motoru'],
    'kumanda-alici-kartlari': ['Kumanda & Alıcı Kartları','KONTROL BİLEŞENLERİ','assets/category-5.jpg','Kepenk ve kapı sistemlerinde uzaktan kontrol ve sinyal yönetimi.','Kepenk|Garaj kapısı|Bahçe kapısı|Bariyer','Kolay kontrol|Yedek kumanda|Akıllı alıcı seçeneği','Frekans uyumu|Kanal sayısı|Anten ve kart','Duvar Butonu|Akıllı Kontrol'],
    'ups-guc-kaynaklari': ['UPS Güç Kaynakları','ENERJİ KESİNTİ DESTEĞİ','assets/category-4.jpg','Elektrik kesintilerinde uygun sistemlerde kontrollü kullanım desteği.','İş yeri|Garaj|Mağaza|Kritik giriş','Kesintide destek|Sistem uyumu|Kontrollü kullanım','Motor uyumluluğu|Akü kapasitesi|Bakım gereksinimi','Manuel Açma Sistemi|Yedek Güç Çözümü']
  };
  const slug = document.body.dataset.product;
  const d = products[slug]; if (!d) return;
  const list = value => value.split('|').map(x => `<li>${x}</li>`).join('');
  document.querySelector('#productMount').innerHTML = `<section class="product-detail-hero"><img src="${d[2]}" alt="${d[0]}"><div class="product-detail-copy"><div class="breadcrumbs">Ana Sayfa / Ürünler / ${d[0]}</div><small>${d[1]}</small><h1>${d[0]}</h1><p>${d[3]}</p><div class="product-points"><span><i data-lucide="shield-check"></i>İhtiyaca özel seçim</span><span><i data-lucide="settings"></i>Otomasyon seçenekleri</span><span><i data-lucide="wrench"></i>Servis desteği</span><span><i data-lucide="calculator"></i>Ön fiyat aracı</span></div><div class="hero-actions"><a class="button primary" href="fiyat-hesapla.html">Fiyat Hesapla</a><a class="button outline" href="iletisim.html">Teklif Al</a></div></div></section><section class="page-content"><div class="container detail-sections"><article><h2>Nerelerde Kullanılır?</h2><ul>${list(d[4])}</ul></article><article><h2>Avantajları</h2><ul>${list(d[5])}</ul></article><article><h2>Teknik Seçenekler</h2><ul>${list(d[6])}</ul></article><article><h2>Montaj & Ölçü</h2><p>Net ölçü, montaj yüzeyi, kutu ve ray alanı keşif sırasında değerlendirilir.</p></article><article><h2>Bakım & Arıza</h2><p>Kullanım yoğunluğuna göre periyodik kontrol önerilir. Motor, yay ve elektrik sistemine yetkisiz müdahale edilmemelidir.</p><a class="text-link" href="teknik-servis.html">Teknik servise git</a></article><article><h2>Alternatifler</h2><ul>${list(d[7])}</ul><a class="text-link" href="karsilastir.html">Ürünleri karşılaştır</a></article></div><div class="product-bottom-cta"><div><small>BU SİSTEMİ PROJENİZ İÇİN DEĞERLENDİRİN</small><h2>Ölçünüzü girin, ön maliyeti görün.</h2></div><div><a class="button primary" href="fiyat-hesapla.html">Fiyat Hesapla</a><a class="button outline" href="https://wa.me/903122717576">WhatsApp</a></div></div></section>`;
  if (window.lucide) lucide.createIcons();
});
